package by.alexandr7035.gitstat.core

enum class DataSyncStatus {
    PENDING_PROFILE,
    PENDING_REPOSITORIES,
    PENDING_CONTRIBUTIONS,
    SUCCESS,
    FAILED_NETWORK,
    // TODO delete old
    FAILED_NETWORK_WITH_CACHE,
    FAILED_NETWORK_WITH_NO_CACHE,
    AUTHORIZATION_ERROR
}